version: '3.7'

services:

  mysqlbd:
    image: mysql:latestconst fs = require('fs');
  const express = require('express');
  const uuidv4 = require('uuid/v4');
  
  const data = JSON.parse(fs.readFileSync('data.json', 'UTF-8'));
  console.log(data);
  
  const server = express();
  server.use(express.json());
  
  server.post(['/payment', '/credit'], (req, res) => {
console.log(`Incoming request: ${req.path} ${JSON.stringify(req.body)}`);
const {body: {number}} = req;

  const [item] = data.filter(o => o.number === number);
  if (item === undefined) {
  res.status(400).end();
  return;
  }

  res.send({
id: uuidv4(),
status: item.status,
});
});
  
  // get port from environment variable or just use 9999
  server.listen(process.env.PORT || 9999);
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node-app:
    build: ./gate-simulator
    ports:
      - '9999:9999'